version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - '80:80' # Expose directement Angular sur le port 80
    restart: unless-stopped
