version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-app
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    depends_on:
      - angular-app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Fichier de config NGINX personnalisé
      - /etc/letsencrypt:/etc/letsencrypt # Certificats SSL pour HTTPS (via Certbot)
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
